# Generated by Django 5.1.2 on 2024-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.TextField()),
                ('rating', models.FloatField()),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
