# Generated by Django 5.1.2 on 2024-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=55)),
                ('overview', models.TextField()),
                ('genre', models.TextField()),
                ('vote_average', models.FloatField()),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TvShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=55)),
                ('overview', models.TextField()),
                ('genre', models.TextField()),
                ('vote_average', models.FloatField()),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=55)),
                ('first_air_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='poster_url',
            new_name='poster_path',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='rating',
            new_name='vote_average',
        ),
    ]
