# Generated by Django 5.1.2 on 2024-11-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_recommendations_tvshows_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='title',
        ),
    ]
