# Generated by Django 5.1.2 on 2024-11-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_tvshows_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
