# Generated by Django 5.1.2 on 2024-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_movies_title_alter_recommendations_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=75)),
                ('overview', models.TextField()),
                ('genre', models.TextField()),
                ('vote_average', models.FloatField()),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
