# Generated by Django 5.1.2 on 2024-11-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(to='cinema.genres'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='genre',
            field=models.ManyToManyField(to='cinema.genres'),
        ),
    ]
