# Generated by Django 5.1.2 on 2024-11-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_remove_genres_genre_remove_tvshows_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='title',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='vote_average',
        ),
        migrations.AlterField(
            model_name='genres',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
