# Generated by Django 5.1.2 on 2024-11-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_genres_overview_remove_genres_poster_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='first_air_date',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='name',
        ),
        migrations.AddField(
            model_name='tvshows',
            name='genre',
            field=models.ManyToManyField(blank=True, to='cinema.genres'),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(blank=True, to='cinema.genres'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='genre',
            field=models.ManyToManyField(blank=True, to='cinema.genres'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
