# Generated by Django 5.1.2 on 2024-11-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_tvshows_first_air_date_remove_tvshows_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='cinema.genres')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
