# Generated by Django 5.1.2 on 2024-12-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
