# Generated by Django 5.1.2 on 2024-12-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_cartoon_backdrop_path_movies_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='poster_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='poster_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='backdrop_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='poster_path',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
    ]
