# Generated by Django 5.1.2 on 2024-12-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_cartoon_slug_movies_slug_recommendations_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
