# Generated by Django 5.1.2 on 2024-12-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_cartoon_number_of_seasons_cartoon_runtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='number_of_seasons',
        ),
    ]
