# Generated by Django 5.1.2 on 2024-12-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_remove_movies_number_of_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
