# Generated by Django 5.1.2 on 2025-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_alter_cartoon_slug_alter_movies_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='en_title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='en_title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='en_title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='en_title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
