# Generated by Django 5.1.2 on 2025-01-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_cartoon_en_title_movies_en_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartoon',
            old_name='en_title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='en_title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='recommendations',
            old_name='en_title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='en_title',
            new_name='title_en',
        ),
    ]
