# Generated by Django 5.1.2 on 2025-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_reviews_content_type_reviews_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='object_id',
        ),
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
