# Generated by Django 5.1.2 on 2025-01-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_alter_cartoon_genre_alter_cartoon_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='genre',
            field=models.ManyToManyField(blank=True, db_index=True, to='cinema.genres'),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(blank=True, db_index=True, to='cinema.genres'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='genre',
            field=models.ManyToManyField(blank=True, db_index=True, to='cinema.genres'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='genre',
            field=models.ManyToManyField(blank=True, db_index=True, to='cinema.genres'),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
    ]
