# Generated by Django 5.1.2 on 2025-01-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_alter_cartoon_genre_alter_cartoon_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoon',
            options={'verbose_name': 'Cartoon', 'verbose_name_plural': 'Cartoons'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name': 'recommendation', 'verbose_name_plural': 'recommendations'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='tvshows',
            options={'verbose_name': 'Tvshow', 'verbose_name_plural': 'Tvshows'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='cinema.movies'),
        ),
    ]
