# Generated by Django 5.1.2 on 2025-01-23 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_alter_cartoon_options_alter_genres_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='movie',
        ),
        migrations.AddField(
            model_name='reviews',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
